databases:
  - name: rock_paper_scissors
    plan: free
    databaseName: rock_paper_scissors
    user: pavel

services:
  - type: web
    name: rock_paper_scissors
    env: python3.10.6
    plan: free
    buildCommand: "./build.sh"
    startCommand: "daphne rock_paper_scissors.asgi:application" 
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: rock_paper_scissors
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4