# Generated by Django 4.1.4 on 2023-01-09 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_game'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='game_owner',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='game_participant',
            new_name='participant',
        ),
    ]
