# Generated by Django 4.1.4 on 2023-01-09 09:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_rename_game_owner_game_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_end_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='participant',
            field=models.ManyToManyField(blank=True, related_name='participant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='game',
            name='winner',
            field=models.PositiveIntegerField(blank=True, choices=[('ow', models.ManyToManyField(related_name='owner', to=settings.AUTH_USER_MODEL)), ('pa', models.ManyToManyField(blank=True, related_name='participant', to=settings.AUTH_USER_MODEL))]),
        ),
    ]
