# Generated by Django 4.1.4 on 2023-01-10 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_game_game_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='participant',
        ),
        migrations.AddField(
            model_name='game',
            name='opponent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opponent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='game',
            name='owner',
        ),
        migrations.AddField(
            model_name='game',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
