# Generated by Django 4.1.4 on 2023-01-10 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_remove_game_participant_game_opponent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='opponent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opponent', to=settings.AUTH_USER_MODEL),
        ),
    ]
