# Generated by Django 4.1.4 on 2023-01-11 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_game_owner_weapon_alter_game_opponent'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='opponent_weapon',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='opponent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opponent', to=settings.AUTH_USER_MODEL),
        ),
    ]
