# Generated by Django 4.1.4 on 2023-01-11 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_game_opponent_weapon_alter_game_opponent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='opponent_weapon',
            field=models.CharField(choices=[('no', 'no_weapon'), ('r', 'rock'), ('p', 'paper'), ('s', 'scissors')], default='no', max_length=2),
        ),
        migrations.AlterField(
            model_name='game',
            name='owner_weapon',
            field=models.CharField(choices=[('no', 'no_weapon'), ('r', 'rock'), ('p', 'paper'), ('s', 'scissors')], default='no', max_length=2),
        ),
    ]
