# Generated by Django 4.1.4 on 2023-01-11 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_alter_game_opponent_weapon_alter_game_owner_weapon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='opponent_weapon',
        ),
        migrations.RemoveField(
            model_name='game',
            name='owner_weapon',
        ),
    ]
