# Generated by Django 4.1.4 on 2023-01-13 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_game_owner_chanel_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='owner_chanel_name',
        ),
    ]
