# Generated by Django 4.1.4 on 2023-01-13 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_remove_game_owner_chanel_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test_model',
        ),
    ]
