# Generated by Django 4.1.4 on 2023-01-18 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0017_alter_game_winner'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, help_text='Enter your date of birth', null=True)),
                ('game_palayed', models.PositiveIntegerField(default=0)),
                ('game_won', models.PositiveIntegerField(default=0)),
                ('short_bio', models.TextField(blank=True, help_text='Enter your short bio', max_length=1000, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
